version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
      - /app/node_modules 
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true